# golangci-lint configuration
# https://golangci-lint.run/usage/configuration/

version: "2" # Note: While the version number itself is often fine, setting it to "2" (string) is sometimes preferred for strict YAML parsers.

run:
  timeout: 5m
  tests: true
  modules-download-mode: readonly

linters:
  enable:
    # Default linters
    - errcheck
    - govet
    - ineffassign
    - staticcheck
    - unused
    # Additional recommended linters
    - misspell
    - revive
    - unconvert
    - unparam
    - whitespace
    - gocyclo
    - dupl
    - goconst
    - gosec
    - prealloc
    - copyloopvar
    - nilerr

  disable:
    - exhaustive
    - exhaustruct
    - varnamelen
    - wrapcheck
    - nlreturn
    - wsl

issues:
  # Maximum issues count per one linter
  max-issues-per-linter: 50

  # Maximum count of issues with the same text
  max-same-issues: 3

  # Show only new issues
  new: false
